
# 路径配置
paths:
  pixiv_dir : /mnt/photo/Pixiv
  all_pic:
    - /mnt/photo/Pixiv
    - /mnt/photo/画师
  log_path : /mnt/nfs/Config/Log/Pixiv

# 链接配置
links:
  logo_pixiv : https://lsky.pantheon.center/image/2022/11/20/637a374fa4aca.jpeg
  head_bark : https://bark.pantheon.center/WSeN8LCGbCDZqHAJMTmeHP

# Headers配置
headers:
  referer: https://www.pixiv.net/ranking.php?mode=daily&content=illust
  cookie: _im_vid=01GQCX73FXBEW22BB0WVHXR401; _fbp=fb.1.1674396763223.37132445; __utma=235335808.1116251316.1674396762.1674633889.1674656386.6; __utmb=235335808.2.10.1674656386; __utmc=235335808; __utmv=235335808.|2=login%20ever=yes=1^3=plan=normal=1^5=gender=male=1^6=user_id=90529190=1^9=p_ab_id=1=1^10=p_ab_id_2=4=1^11=lang=zh=1; __utmz=235335808.1674401888.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _ga=GA1.1.1116251316.1674396762; _ga_75BBYNYN9J=GS1.1.1674656386.8.1.1674656397.0.0.0; __cf_bm=gnWlhNz.PSVZFqm8knxxpYeu081yn7xqmO7Ndyjj9Gc-1674656387-0-AQvlSyLXn5MVr2+N7386shXLF/Fsb12B3niWAwk/fLNMMUrMs+XoPtP9knuAah3egT90ehXdVYxgNEMLqjg3jDGcXLS4Mbfyn+Da93upWYIsSuBCzGYk7/WC/Y5wr6VRJETj2SoKfZl7dsPu94POi1YzMKqdnQHTottKwrrWAuwbfNc6WMJUcAT1tF4K08H3glFY1P833C5pLm11hT8MmN0=; PHPSESSID=90529190_jkIDly6jy9CkhsFWoA5kjokanoEqQkEn; __utmt=1; a_type=0; b_type=1; c_type=22; privacy_policy_notification=0; _ga_MZ1NL4PHH0=GS1.1.1674633912.3.1.1674633965.0.0.0; device_token=aa64336f330ae88c207814dca2c5ced1; privacy_policy_agreement=5; _gid=GA1.2.235656553.1674582691; tag_view_ranking=Lt-oEicbBr~RTJMXD26Ak~uW5495Nhg-~yTFlPOVybE~7ebIzNRkdM~b3tIEUsHql~Qw2RLEQgKY~jH0uD88V6F~jhuUT0OJva~EZQqoW9r8g~PEWvBxU9pH~-t_IAEknVh~RlJg_oCwwz~EmhsFxSBo-~R4YyPA5U1t~QOlvfk_Wxj~hvsnPcI8Rg~D0nMcn6oGk~_pwIgrV8TB~p76wqGJbIo~uusOs0ipBx~lKmQRiaEov~YRDwjaiLZn~5WlN6qpDZj~1HD6lhXO_A~9PI9msRK8Q~mv-jOivdpn~ZKYx1SDf_f~pnCQRVigpy~5NIG-P_d-D; cto_bundle=qGJ8Zl9uaGtIJTJCNkZISmI1ZzJVcHBsNGgzckU5YzN4WFJPRlZoN3J3RXNnUW5FOFpvbTFhJTJGZXViTWt4Qm8lMkYlMkJWYURIa3k2MGxVZFpjWFFPYU1IJTJGbURGSzBOZGxVVm9NRHJxWmNsY0wxQWpzZmlyUzEzbGlLNFRiQWc5UGFsTFpxNVIlMkZIeVhWN3djWGhQMGd6bndOSjdRajZGNlZDUDhDUGFsaDZqY0Y5ZHdIT3R0dGclM0Q; QSI_S_ZN_5hF4My7Ad6VNNAi=v:0:0; login_ever=yes; p_ab_d_id=702090925; p_ab_id=1; p_ab_id_2=4; first_visit_datetime_pc=2022-12-27+09%3A50%3A49; yuid_b=OWEnNRA

